#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

ARG sdk_vsn=0.13.29

FROM digitalasset/daml-sdk:${sdk_vsn}

WORKDIR /home/sdk

COPY ui-backend.conf frontend-config.js /home/sdk/

EXPOSE 7500

CMD ~/.daml/bin/daml navigator -- server ${SANDBOX_HOST} ${SANDBOX_PORT} --port 7500 --config-file ui-backend.conf
