#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

ARG sdk_vsn=0.13.27

FROM digitalasset/daml-sdk:${sdk_vsn}

WORKDIR /home/sdk

COPY target/supplychain.dar /home/sdk/

EXPOSE 7600

CMD ~/.daml/bin/daml sandbox -- --port 7600 --scenario DA.RefApps.SupplyChain.Scenarios:setup supplychain.dar
