FROM ubuntu:18.04

WORKDIR /home/sdk

# COPY ui-backend.conf frontend-config.js /home/sdk/
COPY ui-backend.conf /home/sdk/

RUN /bin/bash -c "apt-get update --no-show-upgraded &&  apt-get install curl openjdk-8-jdk -y"
RUN /bin/bash -c "curl -L https://github.com/digital-asset/daml/releases/download/v0.12.20/daml-sdk-0.12.20-linux.tar.gz -o daml-sdk-0.12.20-linux.tar.gz && \
                  tar -zxvf daml-sdk-0.12.20-linux.tar.gz && \
                  cd sdk-0.12.20 && \
                  ./install.sh && \
                  cd - && \
                  rm -rf sdk-0.12.20"

EXPOSE 7500

CMD ~/.daml/bin/daml navigator -- server ${SANDBOX_HOST} ${SANDBOX_PORT} --port 7500 --config-file ui-backend.conf
