#!/usr/bin/env bash
#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

PORT=${1:-6865}

export PIPENV_PIPFILE=scripts/Pipfile
exec pipenv run scripts/startTriggers.py "$PORT"
