#!/usr/bin/env bash
#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

HOST=${1:-localhost}
PORT=${2:-6865}

export PIPENV_PIPFILE=scripts/Pipfile
exec pipenv run scripts/startTriggers.py "$HOST" "$PORT"
